### ISSUE TITLE
Review and update data dictionary

### ISSUE THREAD

**Issue by mianzg** [openwashdata/saniabidjan#1]
Hi @coulbyph,

I have set up the data package. The raw data is cleaned based on your capstone project code. We are missing the detailed documentation of what each variable means. 

Please help to review and update the data dictionary: https://github.com/openwashdata/saniabidjan/blob/main/data-raw/dictionary.csv

You can refer to the following instructions.

**Comment by mianzg** [comment]
I prepare the following steps:

1. Go to https://github.com/openwashdata/saniabidjan/blob/main/data-raw/dictionary.csv and Download the file.

<img width="1030" alt="download" src="https://github.com/openwashdata/boreholefuncmwi/assets/22420281/2f9933ed-6b37-4297-a554-14c12b8edcd3">

2. Open your downloaded `dictionary.csv` with Excel

3. Edit the column `description` for all the rows we discussed above, and SAVE it to csvfile 

4. Go to https://github.com/openwashdata/saniabidjan/tree/main/data-raw and Select `Add File/Upload Files`

![github_add_file](https://github.com/openwashdata/boreholefuncmwi/assets/22420281/82215642-7370-4aa5-b294-f6edc2cf4fe1)

**5. Upload 
    a. Upload the revised `dictionary.csv` file
    b. Write the commit message
    c. Select the option "Create a new branch", write the name as "dictionary" 
    d. Click the green button to Propose the change.**

![upload](https://github.com/openwashdata/boreholefuncmwi/assets/22420281/c39d267a-b991-4680-91fe-d07e963774f6)

**Comment by coulbyph** [comment]
@mianzg  I've just finished the requested tasks. 
Please let me know if there are any improvements to make.

**Comment by mianzg** [comment]
@coulbyph Thanks! This is great. I made some changes to include possible categories where you can review on https://github.com/openwashdata/saniabidjan?tab=readme-ov-file#data

I would like to clarify a few variable description.

1. education | factor | Level of education of respondents, options including (1) no, (2) primary, (3) coranic, (4) high school, and (5) graduate.

- What do you mean by "graduate"?
- Are "coranic" and "high school" alternative education options? Or "coranic" is a school in between primary and high school?


2. What is "free host" in "status"?
3. What is the unit for "empty_freq_yr", i.e., what do 1, 2, and 3 mean here?
4. What is the unit for "cont_empty_wk"? week?
5. What is the unit for "empty_price"?
6. What is the yes/no question for "lat_facilities", "tank_presence", "waste_cont"? The current description is not clear enough.

**Comment by coulbyph** [comment]
Hi @mianzg !
*(1) no=  The interview didn't go to school (2) primary= The survey has a elementary level, (3) coranic =The investigation went to Quranic school, (4) high school=The survey has a high school level, and (5) graduate= The survey has university status.

* "free host" = The survey is hosted for free
* the unit for "empty_freq_yr = Numbers of times the septic tank is emptied during the year
* the unit for "cont_empty_wk"= Number of times the rubbish container is emptied per week
* "empty_price"= Septic tank emptying prices in CFA
* the yes/no question for "lat_facilities", "tank_presence", "waste_cont"= yes (the household has latrines facilities/septic tanks/waste container). no (the household has not latrines facilities/septic tanks/waste container).


Please, let me know if you need more description. Thanks!
