### ISSUE TITLE
Update data author and contributor information

### ISSUE THREAD

**Issue by mianzg** [openwashdata/saniabidjan#2]
@coulbyph Hi, the current data package include you and our package developer as the authors.

Please provide all other data authors/contributors for this dataset if you are aware of with the format:

First Name:
Family Name:
Email:
ORCiD (if available):

**Comment by coulbyph** [comment]
@mianzg Hi, 
First Name: Kouassi
Family Name: Dongo
Email: kdongo8@gmail.com 

Thanks a lot!
